# Global configuration for the workflow "workflow-smk-ont-basecalling-correction"

# Path to the samplesheet (must be TSV with columns: sample_name, file_path)
samplesheet: "/home/sebastian/Data/Git/project-4mrgn-assembly/samples/sample-sheet_4mrgn_test-1.tsv"        

# Paths to the Dorado installation and the needed models (needs to be modified to fit the users installation paths)
dorado_bin: "/home/sebastian/Tools/dorado-0.9.6-linux-x64/bin/dorado"     # TO DO: add code for an online/offline switch.
dorado_sup_model: "/home/sebastian/Tools/dorado-0.9.6-linux-x64/models/dna_r10.4.1_e8.2_400bps_sup@v4.1.0"  # TO DO: add code for an online/offline switch.
dorado_correction_model: "/home/sebastian/Tools/dorado-0.9.6-linux-x64/models/herro-v1"   # TO DO: add code for an online/offline switch.

# Dorado kit (needs to be modified to fit the users parameters)
dorado_kit: "SQK-NBD114-24"

# Paths to the pod5 installation (is installed via conda in this path if online; otherwise needs to be modified to fit the users installation paths or be included in PATH)
pod5_convert_bin: "pod5"    # TO DO: add code for an online/offline switch.

# Resources                 # TO DO: allocate these within the modules?
cpu_correct: 64
cpu_basecall: 64
cpu_convert: 16

mem_correct: 256000    # 256gb 
mem_basecall: 256000   # 256gb
mem_convert: 4000       # 4gb

gpu_correct: 8
gpu_basecall: 8