# Global configuration for the workflow "workflow-smk-ont-basecalling-correction"

# Path to the samplesheet (must be TSV with columns: sample_name, file_path)
samplesheet: "/gpfs/project/projects/medbioinf/users/semey101/ont-basecalling-correction/samples/sample-sheet_4mrgn_test-1.tsv"

# Paths to the Dorado installation and the needed models (needs to be modified to fit the users installation paths)
dorado_bin_old: "/gpfs/project/projects/medbioinf/users/semey101/software/dorado-0.7.2-linux-x64/bin/dorado"
dorado_bin_new: "/gpfs/project/projects/medbioinf/users/semey101/software/dorado-0.9.2-linux-x64/bin/dorado"
dorado_sup_model_old: "/gpfs/project/projects/medbioinf/users/semey101/ont-basecalling-correction/dorado_models/dna_r10.4.1_e8.2_400bps_sup@v4.1.0"
dorado_sup_model_new: "/gpfs/project/projects/medbioinf/users/semey101/ont-basecalling-correction/dorado_models/dna_r10.4.1_e8.2_400bps_sup@v5.2.0"
dorado_correction_model: "/gpfs/project/projects/medbioinf/users/semey101/ont-basecalling-correction/dorado_models/herro-v1"

# Dorado kit (needs to be modified to fit the users parameters)
dorado_kit: "SQK-NBD114-24"

# Paths to the pod5 installation (is installed via conda in this path if online; otherwise needs to be modified to fit the users installation paths or be included in PATH)
pod5_convert_bin: "pod5"

# Resources

gpu_correct: 1
gpu_basecall: 1

cpu_correct: 8
cpu_basecall: 8
cpu_convert: 4

mem_correct: 128000
mem_basecall: 128000
mem_convert: 4000

walltime_correct: 1
walltime_basecall: 1
walltime_convert: 1